List of Data Needed for Realistic Atmospheric Simulations:

1. Source Characteristics (Crucial Input):

Emission Rate Data:

Rate of Emission: Measure the amount of each target gas (CH4, H2S, NH3, CO2) being released from the source material per unit of time (e.g., grams/hour, kg/day , liters/minute). This must be measured under controlled conditions to isolate the source strength.

Dependency on Environmental Conditions: Characterize how the emission rate changes based on key environmental factors like Temperature and Humidity of the source material and surrounding air.

Dependency on Time: Characterize how the emission rate changes over the lifecycle of the source material (e.g., emissions from a fresh patty versus one that has been decomposing for a week).

Dependency on Mass/Area: If scaling the source, understand how the emission rate scales with the amount of material (total mass, total surface area covered, depth of a pile).

Source Geometry:

Location: Precise coordinates or location within the simulation space.

Shape and Dimensions: How the source material is physically arranged (e.g., spread thinly over a large area, piled in a heap, contained in bins). This affects the surface area exposed for emission and internal conditions.

Heat Emission Rate (Optional, but improves realism):

If simulating temperature distribution, quantify the rate of heat being generated by the decomposition process (e.g., Watts or BTU/hr).

2. Spatial Characteristics (Defining the Simulation Domain):

Geometry of the Space:

Detailed dimensions (Length, Width, Height) of the room, building, or enclosed area.

Complex features (sloped roofs, different floor levels, internal partitions).

Internal Obstacles:

Location and dimensions of significant objects that block or redirect airflow (walls, columns, large equipment, furniture).

Openings:

Location, dimensions, and type of all doors, windows, vents, fans, or other passive and active openings that allow air exchange with the outside or other zones.

3. Airflow & Ventilation Characteristics (How Air Moves):

Ventilation System Data (if mechanical):

Location and type of supply and exhaust fans/vents.

Airflow rates for each fan under different operating conditions (e.g., different speeds, static pressure).

Schedule of operation (when fans are on/off, speed changes).

Ductwork geometry (if air is supplied or exhausted via ducts).

Natural Ventilation Data:

Information on how windows/doors are operated (open/closed, size of opening).

External Wind Speed and Wind Direction data (as these drive natural ventilation through openings).

External and Internal Temperature Differences (stack effect).

Internal Airflow Patterns (for Model Validation/Tuning):

Measurements of air velocity and direction at multiple points within the space. This helps validate if the simulation's prediction of air movement is correct. Anemometers are needed for this.

4. Environmental & Boundary Conditions:

Initial Conditions:

Gas Concentrations of all target gases throughout the simulation space at the start time of the simulation.

Temperature and Humidity throughout the space at the start time.

Inlet Conditions:

Gas Concentrations of all target gases in the air entering the simulation space (e.g., outdoor ambient concentrations).

Temperature and Humidity of the incoming air.

Surface Properties (Optional, for detailed models):

Material properties of walls, floor, ceiling (e.g., roughness, thermal conductivity, emissivity).

Adsorption/Absorption characteristics of surfaces for the target gases.

5. Validation Data (To Check Simulation Accuracy):

Time Series Concentration Data:

Continuous (high-frequency, like your minute-by-minute data) measurements of all target gas concentrations at one or, ideally, multiple distinct locations within the simulation space over a representative period.

Time Series Environmental Data:

Continuous measurements of Temperature and Humidity at the same locations and times as the concentration data.

Operational Logs:

Records of when ventilation systems were operated, doors/windows were opened/closed, or any activities that might affect air quality or airflow occurred during the data collection period.

Collecting these categories of data allows you to create a digital twin of your space and source, enabling realistic predictions of atmospheric gas concentrations under various scenarios. The most challenging and critical data point is often obtaining accurate Source Emission Rates.